### ISSUE TITLE
Add support for the x.com domain

### ISSUE THREAD

**Issue by deivpaukst** [AucT/twitter2nitter#5]
With Twitter now also using the x.com domain it would be neat if it could also be translated to a nitter instace.

**Comment by AucT** [comment]
Thanks for your report
this commit https://github.com/AucT/twitter2nitter/commit/d25614df099d5a245cea753eea4161687f1de215
adds x.com redirect

**Comment by deivpaukst** [comment]
Hello, I've noticed that x.com does not appear in the supported links list:
![Screenshot_20230817-110829_Settings](https://github.com/AucT/twitter2nitter/assets/81613945/0d858fa6-3611-4b32-9524-85b15094108d)
Adding the domain to the list would be the final cherry on top for this feature request. 😀

**Comment by AucT** [comment]
Forgot to add to manifest. But I've tested it - it is working even without intent filter, because x redirects to twitter)
The 1.8 version will have it.

Again thanks for report.

Hope nitter instances will work soon. I see they stopped working.

**Comment by deivpaukst** [comment]
Thank you for the app!
And yeah, I hope so too. The only thing that twitter is "good" at seems to be limiting people's ability to access it.

Slava Ukraini!
